### ISSUE TITLE
cmake not working, make directory does not exist

### ISSUE THREAD

**Issue by jgiesen** [FLIR/BosonUSB#1]
Hello,
i get following error, when i use cmake:

> ~/BosonUSB$ cmake . make
> CMake Error: The source directory "/home/jens/BosonUSB/make" does not exist.

**Comment by JimKlingshirn** [comment]
I think the readme is  wrong.  It's a two step process, first running cmake, and then running make:
`cmake .`
`make`

**Comment by JimKlingshirn** [comment]
I've updated the readme.  Thanks for the feedback!

**Comment by jgiesen** [comment]
thanks alot!
now i learned that "cmake . && make" works also.

**Comment by ghost** [comment]
Sorry for late answer here... yes it was a typo. 
just a note. 
cmake .  -> creates the makefile and CMmakeFiles directory. You do it once.
make -> compile, you do it every time  you do modifications
make clean -> to start fresh, but doesn't delete the CMakeCache, Makefile, CMakeFiles.

so:  cmake . && make will add unnecessary work  ... 

Thank you Jim for fixing it.
