### ISSUE TITLE
Add way to capture a certain number of frames. 

### ISSUE THREAD

**Issue by RustyRaptor** [FLIR/BosonUSB#10]
It is useful to be able to but a limit on the frames in the arguments so you can capture a certain number of frames. While indeed the user could set a sleep timer to time the program it is much more difficult to write a script that stops after a certain frame.

**Comment by ghost** [comment]
It is a nice feature, there is a second version of this one which captures a limit of frames but skipping in between. Captures X frames out on Y for a total of Z... We never merged here to avoid adding more complexity to the code.
