### ISSUE TITLE
How to get real thermal data?

### ISSUE THREAD

**Issue by spk921** [FLIR/BosonUSB#14]
We are trying to use the thermal information and get the real temperature information. 
Do you have any idea that how we can do it?

**Comment by josephduchesne** [comment]
This appears to be able to do what you're after, but in my initial testing it didn't seem to work as expected.
https://rdrr.io/cran/Thermimage/man/raw2temp.html

**Comment by andrespmt** [comment]
BosonUSB is meant for Boson. Currently Boson cameras are not calibrated to
be radiometric. It means that even if they provide 16bits and you apply the
formulas described, there is an internal calibration that didn't have.
Other cameras at FLIR are Radiometric which means that what is said in that
link will work. With Boson it is not guarantee nor expected to be accurate
on that.
If in the future Boson product line come up with  a RadiometricBoson then
could be, not sure if with the exact same formula.
