### ISSUE TITLE
Using BosonSDK fails to open port for Linux

### ISSUE THREAD

**Issue by JonathanWPOC** [FLIR/BosonUSB#15]
Hi Everyone,

I've been trying to use the **BosonSDK** on Linux Ubuntu 18.04.2 LTS with the USB camera, and I have been having an issue getting the port to open.  I have had success on Windows 10.  I have also have success using OpenCV in Linux to read from the IR Camera.

Tried using the "make" command to remake the binary .so files.  Compiled Successfully.

Running the command **dmesg** to find port number.   This tells me that the USB device is at ttyACM0.  However I'm seeing some uvcvideo issues here.  The FLIR Boson camera does work in applications like Cheese.

> [274557.577628] usb 1-3: USB disconnect, device number 19
> [274564.366993] usb 1-3: new high-speed USB device number 20 using xhci_hcd
> [274564.517588] usb 1-3: New USB device found, idVendor=09cb, idProduct=4007
> [274564.517594] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [274564.517598] usb 1-3: Product: Boson
> [274564.517602] usb 1-3: Manufacturer: FLIR
> [274564.517606] usb 1-3: SerialNumber: 33226
> [274564.519501] uvcvideo: Unknown video format 3132564e-0000-0010-8000-00aa00389b71
> [274564.519513] uvcvideo: Found UVC 1.00 device Boson (09cb:4007)
> [274564.521490] uvcvideo 1-3:1.0: Entity type for entity Processing 3 was not initialized!
> [274564.521495] uvcvideo 1-3:1.0: Entity type for entity Camera 1 was not initialized!
> [274564.522288] cdc_acm 1-3:1.2: ttyACM0: USB ACM device

The Python code that I'm running is here.  Fails on the initialize method. 
```
from BosonSDK import *
def main():
    #myport = pyClient.Initialize(manualport="/dev/ttyUSB0")  # Not Using
    myport = pyClient.Initialize(manualport="/dev/ttyACM0")  # Using from above.
    #<--- Fails Here
    pyClient.bosonRunFFC()
    result, serialnumber = pyClient.bosonGetCameraSN()
    pyClient.Close(myport)

```

The Failed Output, With Some additional Debug information:

> Testing Code
> PortNum: 16 // /dev/ttyACM0
> BaudRate: 921600
> Traceback (most recent call last):
>   File "/home/username/SVN/Code/FLIR_BosonCameraSDK/main_apitest.py", line 33, in <module>
>     main()
>   File "/home/username/SVN/Code/FLIR_BosonCameraSDK/main_apitest.py", line 20, in main
>     myport = pyClient.Initialize(manualport="/dev/ttyACM0")  # or manualport="COM7" on Windows
>   File "/media/username/data1T/SVN/Code/FLIR_BosonCameraSDK/BosonSDK/ClientFiles_Python/Client_API.py", line 20, in Initialize
>     uart.OpenPort(manual_port=manualport,manual_baud=manualbaud)
>   File "/media/username/data1T/SVN/Code/FLIR_BosonCameraSDK/BosonSDK/FSLP_Files/UART_HalfDuplex.py", line 200, in OpenPort
>     raise IOError("Failed to open COM port {:d}!, Portnum: {:d}, BaudRate: {:d}".format(ret,portnum,baudrate))
> OSError: Failed to open COM port -1!, Portnum: 16, BaudRate: 921600

Since this issue happens in the compiled C code, It might be due to a driver issue. Any help would be appreciated.  Thanks!

SDK Download Link: Click on Boson SDK &amp; IDD, BosonSDK_rev206.zip
[https://www.flir.com/support/products/boson#Resources](https://www.flir.com/support/products/boson#Resources)

SDK Manual:
[https://www.flir.com/globalassets/imported-assets/document/boson_sdk_documentation_9hz-v11412-and-later.pdf](https://www.flir.com/globalassets/imported-assets/document/boson_sdk_documentation_9hz-v11412-and-later.pdf)

**Comment by ghost** [comment]
Sorry, BosonUSB doesn't use SDK. that issue needs to be posted in a different forum.
