### ISSUE TITLE
Output is Grayscale

### ISSUE THREAD

**Issue by ahmedosama9777** [FLIR/BosonUSB#16]
I am using the 8-bit mode. and my output is a grayscale image, is cvtcolor not working?

**Comment by ghost** [comment]
should be working. We had an issue where color planes where swapped but got fixed.  Basically if you open in YUV mode ( not RAW ) then if Boson is configured to use color LUTs you will see them ....

**Comment by ghost** [comment]
./BosonUSB y  ->  opens Boson320 /dev/video0  in AGC-8bits mode

AGC mode will display colors if Boson does. Let us know.

**Comment by ahmedosama9777** [comment]
That’s what I am using. I get a .tiff file that is grayscale, what’s weird is that the .tiff file has 3 channels, and they are all equal to each other when I separate them.

**Comment by ghost** [comment]
I have tested it and it works, i am getting the TIFFs colorized. What i have done.
- I configured the Boson to provide colors. In my case i used rawBoson from the command line, but you can use the UI or any other tool.
- I opened  the video using BosonUSB and it was colorized ( BosonUSB sB y ) 
- I quit and run again BosonUSB with the recording enable.  Video was colorized and I opened the file and it looks the same than the video.
- 
So basically, if your video is gray scale , your recording will be grey scale. 

The commands i use:
sudo ./rawBoson -p/dev/ttyACM0 -b921600 c000B0001 x0 x0 x0 x1    ( this is to activate colormap )
sudo ./rawBoson -p/dev/ttyACM0 -b921600 c000B0003 x0 x0 x0 x4    ( to activate one of the maps )
./BosonUSB sB y ftest    ( to display AGC mode while recording )
eog Boson_640_yuv_0.tiff   ( to open the file )

Video and files are colorized.
rawBoson is at Github as well : github.com/FLIR/rawBoson

**Comment by ahmedosama9777** [comment]
Thank you! 

All sorted now.
