### ISSUE TITLE
Configuring Framerate

### ISSUE THREAD

**Issue by AlanTurnage** [FLIR/BosonUSB#5]
I am currently developing an app with the Boson 640 with the USB adapter board. I would like to have the ability to change the framerate of the camera, but so far I have been unsuccessful. What v4l commands should I use to do this? I've tried the following code and a few other things. Any help would be appreciated.
```
struct v4l2_streamparm parm;
parm.type = V4L2_BUF_TYPE_VIDEO_CAPTURE;
parm.parm.capture.timeperframe.numerator = 1;
parm.parm.capture.timeperframe.denominator = 30;
int ret = xioctl(fd, VIDIOC_S_PARM, &parm);
```

**Comment by ghost** [comment]
BosonUSB doesn't support changing the framerate using V4L layer.
There is a USB-UART (ttyACM0) that you can use to send a command to the camera, but the framerate as implemented in V4L is not available in our cameras.  You have some options but not as a variable that you can select a value.

**Comment by AlanTurnage** [comment]
> BosonUSB doesn't support changing the framerate using V4L layer.

That's what I was afraid of..
I assume that's because of the averaging that occurs when switching from 60fps to 30fps instead of actually decreasing the capture rate?

**Comment by AlanTurnage** [comment]
I switched to using the SDK so I can easily configure the frame rate. Now I just need to figure out how to actually get a frame from the camera.

**Comment by ghost** [comment]
BosonUSB shows you a way of getting a video frame. 
SDK configures the camera. 
Glad that you manage it.
