### ISSUE TITLE
White screen on displayed video.

### ISSUE THREAD

**Issue by RustyRaptor** [FLIR/BosonUSB#9]
I compiled opencv and BosonUSB on a raspberry pi but when I run any of the commands the displayed video in the small window is all white. It shows one instant of the camera then it goes all white. Despite this when I save them with f in a folder the captured images all look fine and I can see what's on the camera. Here is what I see in console.

```
./BosonUSB fcap
Boson Capture and Record Video tool v1.0
FLIR Systems

use : 'BosonUSB r' to capture in raw-16 bits mode   (default)
Use : 'BosonUSB y' to capture in agc-8  bits mode
Use : 'BosonUSB z' Zoom to 640x512 (only in RAW) mode  (default ZOOM OFF)
Use : 'BosonUSB f<name>' record TIFFS in Folder <NAME>
Use : 'BosonUSB [0..9]'   to open /dev/Video[0..9]  (default 0)
Use : 'BosonUSB s[b,B]'   b=boson320, B=boson640   (default 320)
Press 'q'  to quit

>>> Folder cap selected to record files
>>> Boson_320 selected
>>> /dev/video0 selected
>>> 16 bits capture selected
>>> Image width  =320
>>> Image height =256
>>> Buffer lenght=163840

** (Boson_320 : RAW16  Linear:24535): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
```
On another note it works fine on my desktop setup so I am not sure how to debug this.
And yet another note I can open the camera in VLC on the same raspberry pi and view the video just fine.

**Comment by ghost** [comment]
Sorry, no idea of this one. it could be that the linear AGC is failing due to some strange pixel data? Have you tried with 8 bits only? if it works i would say that there is a value that is making the AGC fail in the code... but don't have a reason for that.

**Comment by RustyRaptor** [comment]
Ah sorry for not getting back to this. The issue no longer happens after a reinstall. It was likely an issue with my installation of opencv at the time I'll just close this.
